language: go

go:
  - 1.8.x
  - 1.9.x

go_import_path: github.com/playnet-public/gocmd-template

env:
  global:
  - REPO: $TRAVIS_REPO_SLUG
  - VERSION: $TRAVIS_TAG

before_install:
  - make deps

before_script:
  - make test

script:
- make full install
- make full build

after_success:
- make docker

deploy:
  provider: releases
  api_key:
    secure: "${GITHUB_TOKEN}"
  file: build/*
  skip_cleanup: true
  file_glob: true
  overwrite: true
  on:
    repo: playnet-public/gocmd-template
    tags: true
